### ISSUE TITLE
Print Qr Code

### ISSUE THREAD

**Issue by rafaelterada** [edufolly/flutter_bluetooth_serial#1]
Good Morning. I'm connecting to a thermal printer and trying to print a Qr Code. It's possible? Thank you

**Comment by edufolly** [comment]
Probably @rafaelterada,

you only need to know the correct commands. What's the printer's brand?

**Comment by rafaelterada** [comment]
The brand is bematech PP-10B

**Comment by edufolly** [comment]
I used Bematech printers with a network connection, but not with Bluetooth. I believe that it'll work.

**Comment by rafaelterada** [comment]
Would you have an example of bematech code? Thank you
