### ISSUE TITLE
Bluetooth 5 Transfer Speed Slow

### ISSUE THREAD

**Issue by satyajitghana** [edufolly/flutter_bluetooth_serial#102]
While using this library i did a quick test to see how much data i can transfer, i got `average rate = 79914.7081 bytes/s or ~80 kilo bytes / s`

my phone supports 5.0 as well as my raspberry pi 3 has 5.0, but why is the speed so slow ? am i missing something ?

what can i do to increase these speeds ?

**Comment by nightscape** [comment]
Not a 100% sure, but I think the RFCCOMM protocol did not change with Bluetooth 5.0.
This is still quite a low rate.
I have no idea how to improve this tbh...

**Comment by satyajitghana** [comment]
It turns out this speed was enough for my usecase, so its fine :)
