### ISSUE TITLE
Explore discovered devices i.e (FlutterBluetoothSerial.instance.startDiscovery()) does not work on Samsung devices while they work for Oppo mobile phones.

### ISSUE THREAD

**Issue by umamakhalid** [edufolly/flutter_bluetooth_serial#105]
### Steps to reproduce

1. 
2. 
3. 
4. 

### Environment

```
```

**Comment by changhouw** [comment]
We have same issue, try to request permission fine location before discovering

**Comment by vaibhiarora03** [comment]
I am requesting fine location permissions but still the same issue. The devices are discovered once I switch from phone's bluetooth settings.

**Comment by umamakhalid** [comment]
Try giving background location permission

**Comment by vaibhiarora03** [comment]
Tried but same issue.

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>

**Comment by umamakhalid** [comment]
Try asking permissions inside the code. Permission for background location
and other bluetooth locations.

**Comment by umamakhalid** [comment]
1. Give Background Location Permission in Manifest
2. Few mobiles does not work with manifest permission so you also have to ask for permission in the code.
