### ISSUE TITLE
Can you please support windows I have a project that depends on it

### ISSUE THREAD

**Issue by husamhamu** [edufolly/flutter_bluetooth_serial#107]
### Steps to reproduce

1. 
2. 
3. 
4. 

### Environment

```
```

**Comment by edufolly** [comment]
I'll keep this issue open, but I don't know how to implement this. Help wanted.

Best.

**Comment by edufolly** [comment]
Sorry,

we have this issue #69, so this issue is duplicated.

If you have further questions, please reopen this issue or open a new one.

Best.
