### ISSUE TITLE
Printer ZPL

### ISSUE THREAD

**Issue by fgomezgr81** [edufolly/flutter_bluetooth_serial#109]
I am trying to print zpl code through this package, my code is as follows:

 zpl += '''  ^FX Importe total del pedido 
        ^CFA,30 
        ^FO300,${linea}
        ^FDImporte
        ^FS ^FO600,${linea}
        ^FD${encabezado.importe}^FS 
        ^XZ''';

      try {
        BluetoothConnection connection;
        String mac = "00:22:58:3A:60:4B";
        await BluetoothConnection.toAddress(mac).then((_connection) {
          connection = _connection;
        });

        print("Running print");

        print(zpl);
        connection.output.add(utf8.encode(zpl));
        connection.finish();

        print("Complete");
      } catch (exception) {
        print(
            'Cannot connect, exception occured, message:${exception.toString()}');
      }

but it prints the code as it is sent it does not respect the zpl, how can I do it.

**Comment by edufolly** [comment]
Hi @fgomezgr81 

look this issues #92 and #1

Maybe this will help you.

If you have further doubts, reopen this issue or open a new one.
