### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by savs90** [edufolly/flutter_bluetooth_serial#121]
Hey guys. This is not exactly bug , but with flutter 2 announced it would be great if you can upgrade the project to null safety. Null safety is now part of the stable releases. Thanks a lot for the great work!

**Comment by JAICHANGPARK** [comment]
Null Safety~~!!!

**Comment by rus0n** [comment]
any new?

**Comment by vishnuagbly** [comment]
pull request have been made in #122, but it looks like this project has been abandoned

**Comment by CodeDoctorDE** [comment]
can anyone create a new fork which accepts pull requests?

**Comment by CodeDoctorDE** [comment]
What's the new plan? @vishnuagbly

**Comment by ShinyWrench** [comment]
If you just want to get the package working with your program, here's a couple ways to do it.

If you're using VS Code and the Dart and Flutter extensions, you can add this to your .vscode/settings.json (or create it in your project folder with this content):
```
{
    "dart.flutterRunAdditionalArgs": [
        "--no-sound-null-safety"
    ],
    "dart.vmAdditionalArgs": [
        "--no-sound-null-safety"
    ]
}
```
If you don't want to do it that way, you can run your program with this:
`flutter run --no-sound-null-safety`

(https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs)

**Comment by nightscape** [comment]
Corresponding PR is merged. You can try it by using the Git version of this repo.

**Comment by edufolly** [comment]
Version 0.3.0 was published.
