### ISSUE TITLE
reading data through bluetooth

### ISSUE THREAD

**Issue by goldencoder20** [edufolly/flutter_bluetooth_serial#123]
Hi
currently I'm working in a small app connected with a device through bluetooth.
so sending data works fine for me using this function:
void _sendMessage() async {
    connection.output.add(utf8.encode("data here" + "\r\n"));
    await connection.output.allSent;
  }

but I don't know how to read data and print it for example in console
please can you provide a function can solve the issue?
thanks

**Comment by MojamojaK** [comment]
Follow the example

This sets the callback to be called every time data is received
```Dart
connection.input.listen(_onDataReceived).onDone(() {
  if (isDisconnecting) {
    print('Disconnecting locally!');
  } else {
    print('Disconnected remotely!');
  }
  if (this.mounted) {
    setState(() {});
  }
});
```
where the callback `_onDataReceived ` is implemented like this
```Dart
void _onDataReceived(Uint8List packet) {
  try {
    print(utf8.decode(packet.sublist(0, packet.length)));
  } catch (e) {
    setState(() {});
  }
}
```

**Comment by goldencoder20** [comment]
thanks a lot, it works fine now

**Comment by heqikang** [comment]
> Follow the example
> 
> This sets the callback to be called every time data is received
> 
> ```dart
> connection.input.listen(_onDataReceived).onDone(() {
>   if (isDisconnecting) {
>     print('Disconnecting locally!');
>   } else {
>     print('Disconnected remotely!');
>   }
>   if (this.mounted) {
>     setState(() {});
>   }
> });
> ```
> 
> where the callback `_onDataReceived ` is implemented like this
> 
> ```dart
> void _onDataReceived(Uint8List packet) {
>   try {
>     print(utf8.decode(packet));
>   } catch (e) {
>     setState(() {});
>   }
> }
> ```

I sending data works fine, but read data failed

![Snipaste_2021-04-14_18-26-20](https://user-images.githubusercontent.com/20039536/114696861-bb94cb00-9d4f-11eb-83e6-b90dc0e4d315.png)
![Snipaste_2021-04-14_18-26-35](https://user-images.githubusercontent.com/20039536/114696878-c18aac00-9d4f-11eb-8992-a1b4aaeec1f0.png)
