### ISSUE TITLE
Flutter Bluetooth Serial library does not work on iOS

### ISSUE THREAD

**Issue by Moussabaddour** [edufolly/flutter_bluetooth_serial#125]
I run the example on iOS it does not work!!!!
 I got this : 

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel flutter_bluetooth_serial/state:
MissingPluginException(No implementation found for method listen on channel flutter_bluetooth_serial/state)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
<asynchronous suspension>
====================================================================================================

**Comment by edufolly** [comment]
@Moussabaddour iOS doesn't have support. Check this issue: #2
