### ISSUE TITLE
Please, migrate to null-safety

### ISSUE THREAD

**Issue by selmaskopljakovic** [edufolly/flutter_bluetooth_serial#127]
Hello authors,

can you please migrate flutter_bluetooth_serila to null-safety?

Thank you!

**Comment by ShinyWrench** [comment]
If you just want to get the package working with your program, here's a couple ways to do it.

If you're using VS Code and the Dart and Flutter extensions, you can add this to your .vscode/settings.json (or create that file with this content):
```
{
    "dart.flutterRunAdditionalArgs": [
        "--no-sound-null-safety"
    ],
    "dart.vmAdditionalArgs": [
        "--no-sound-null-safety"
    ]
}
```
If you don't want to do it that way, you can run your program with this:
`flutter run --no-sound-null-safety`

(https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs)

**Comment by nightscape** [comment]
I just merged a corresponding PR.
I can't publish new versions yet, but you can try it by using the Git version of this repo.
