### ISSUE TITLE
Find a solution for future maintenance

### ISSUE THREAD

**Issue by nightscape** [edufolly/flutter_bluetooth_serial#128]
Hi @edufolly,

this project seems to be quite important to many people, but you don't seem to have time to maintain it yourself anymore.
I've seen network graphs like this before on Github, and it's a breaking point for many Open Source projects:
![image](https://user-images.githubusercontent.com/35170/117220653-f0a0b480-ae07-11eb-9a05-d9f28695bb7e.png)
In almost all cases, the original author does not have the time or interest to handle the huge amount of issues, questions, pull requests, ... anymore.
It seems that there are a few people willing to help with maintaining this project (please add a 👍  here if you are one of them and actually have time and motivation to answer questions & issues, review pull requests, etc.).
It would be great if you could add contributor or admin rights to a few of them so that this project doesn't die of neglect.
You have invested quite a bit of time and energy yourself!

I would recommend e.g. @kechankrisna and @PsychoXIVI (please 👍  if you'd be willing to become a maintainer), both of whom have submitted very well-written PRs to this project.

**Comment by CodeDoctorDE** [comment]
It would be cool to have a simpler api and an updated api. The latest version is updated 2019

**Comment by nightscape** [comment]
@PsychoXIVI do you have sufficient rights to add additional collaborators?

**Comment by edufolly** [comment]
Hi @nightscape. Please, send me an email if you want to collaborate even more.

**Comment by CodeDoctorDE** [comment]
Any new updates? @edufolly @nightscape

**Comment by nightscape** [comment]
Yes, I do have maintainer rights now and I'm planning to get the null-safety branch merged soon.
Just haven't found the time yet.

**Comment by jahnli** [comment]
> 是的，我现在确实拥有维护者权利，并且我计划尽快合并 null-safety 分支。
> 只是还没找到时间。

Looking forward to the new maintenance, hope to migrate to air security as soon as possible

**Comment by nightscape** [comment]
null-safety branch is merged, along with a few other updates and improvements.
You can try it by using the Git version of this repo.

I'm still lacking the ability to publish to pub.dev.
@edufolly @AgainPsychoX I could set up a Github action to automatically publish Github releases.
Any objections against this?

**Comment by edufolly** [comment]
Version 0.3.0 published. Thanks for all the support.
