### ISSUE TITLE
Warning! Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2. Follow the steps at  https://flutter.dev/go/android-project-migration  to migrate your project.

### ISSUE THREAD

**Issue by emailsubjekt** [edufolly/flutter_bluetooth_serial#132]
When I try to run your github example, I get this wonderful message 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by edufolly** [comment]
Could you help? @nightscape @AgainPsychoX

**Comment by nightscape** [comment]
I'm on it 👍

**Comment by luckycreationsindia** [comment]
Any update on this?

It's creating issue with firebase_messaging background notifications while registering other plugins like shared_preferences (For background notification)

**Comment by nightscape** [comment]
I started working on this here: https://github.com/edufolly/flutter_bluetooth_serial/tree/update_flutter_plugin_v2
Unfortunately, the plugin loading part does not seem to work on that branch and I ran out of time figuring out why.
If anybody could give this a look it would be very much appreciated!

**Comment by luckycreationsindia** [comment]
I did few changes and It's working.

Debugging the code got me to null pointer on activity.

Full Changes can be found here:
https://github.com/luckycreationsindia/flutter_bluetooth_serial/tree/update_flutter_plugin_v2

This also address Future<int> issue with setState and getDeviceBondState Methods as mentioned in this issue:

#139

**Comment by nightscape** [comment]
Thank you @luckycreationsindia, this was the missing part!

@edufolly would you mind creating a new release out of this?

**Comment by edufolly** [comment]
Thanks, @luckycreationsindia!

And thanks @nightscape again!

Sorry about the delay, I've been published now version ```0.4.0```.
