### ISSUE TITLE
Only Android Support?

### ISSUE THREAD

**Issue by Celpear** [edufolly/flutter_bluetooth_serial#133]
Hello,
after trying your package on an IOS device, I received an error message that the IOS methods cannot be accessed. Has this problem occurred before?

### Problem summary
![image](https://user-images.githubusercontent.com/28110865/119848059-c8d6d500-bf0b-11eb-8890-9aaffb141e90.png)

### Steps to reproduce

After trying the Discover function:
![image](https://user-images.githubusercontent.com/28110865/119844384-adb69600-bf08-11eb-8773-105cd57004c9.png)
I get this msg:
![image](https://user-images.githubusercontent.com/28110865/119848059-c8d6d500-bf0b-11eb-8890-9aaffb141e90.png)

The getState method does not work on IOS devices either.
I have also checked the IOS permissions (Info.plist). But they seem to be ok.
When searching for the methods, I couldn't find them in the native code.

### Environment

Flutter Version:
Flutter 2.0.6 • channel stable 
Framework • revision 1d9032c7e1 (4 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

It was installed on an IPhone SE 
IOS 14.6 installed and tested.

Can you help me further?
Thank you very much!

**Comment by MojamojaK** [comment]
This library only supports Android

**Comment by Celpear** [comment]
That is a pity. In pub.dev it says IOS support. :(

**Comment by Moussabaddour** [comment]
unfortunately,

That plugin supports the legacy RFCOMM profile. This profile is not available to apps on iOS.

This plugin cannot work with iOS (Nor can any plugin that uses the RFCOMM profile).

**Comment by edufolly** [comment]
@Celpear iOS doesn't have support. Check this issue: #2
