### ISSUE TITLE
Error while connecting bluetooth

### ISSUE THREAD

**Issue by dharmita1990** [edufolly/flutter_bluetooth_serial#16]
While connecting Bluetooth with other device getting following error:

getBluetoothService() called with no BluetoothManagerCallback
D/FlutterBluePlugin(29010): android.bluetooth.device.action.ACL_CONNECTED
E/FlutterBluePlugin(29010): read failed, socket might closed or timeout, read ret: -1
E/FlutterBluePlugin(29010): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
E/FlutterBluePlugin(29010): 	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:686)
E/FlutterBluePlugin(29010): 	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:698)
E/FlutterBluePlugin(29010): 	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:375)
E/FlutterBluePlugin(29010): 	at io.github.edufolly.flutterbluetoothserial.FlutterBluetoothSerialPlugin.lambda$connect$0(FlutterBluetoothSerialPlugin.java:278)

**Comment by vguttmann** [comment]
What did you do to fix it? Where did you have an error?
