### ISSUE TITLE
must be received once and sent once？

### ISSUE THREAD

**Issue by zxj17815** [edufolly/flutter_bluetooth_serial#19]
After receiving ,it must click “send” to receive the next message？
No matter how much the sender sends, it will not be printed automatically. It will only be printed once after clicking “send”.

**Comment by zxj17815** [comment]
I mean，when I run the demo, I find it must send before get the messsage,if not it will lost the message.
How should I modify it？

**Comment by PsychoXIVI** [comment]
Chat example of #35 is working better than old version: Both Server and client (Android) can send multiple messages, and the messages are received and displayed for the recipient as fast as possible.
