### ISSUE TITLE
Pairing

### ISSUE THREAD

**Issue by FWeissenb** [edufolly/flutter_bluetooth_serial#34]
Hi,

After implementing device search (thx @dharmita1990) I want to implement bonding with a pin code.

Problem: needed methods are API level 19 (Android 4.4) but the current API level is 18 (Jelly Bean 4.3).
Can I upgrade the API level @edufolly ? 
API 18 is used by 0.5% of current devices. (https://developer.android.com/about/dashboards)

**Comment by edufolly** [comment]
Hi @FWeissenb, 

you should upgrade. No problem.

Create a PR and I'll publish as soon as possible.

Thanks.

**Comment by PsychoXIVI** [comment]
I will look into it just after merging #35 PR

**Comment by PsychoXIVI** [comment]
See PR #38

**Comment by PsychoXIVI** [comment]
Closed by #38
