### ISSUE TITLE
getBondedDevices throws [Failed resolution of: Landroidx/core/content/ContextCompat];

### ISSUE THREAD

**Issue by n00ne1mportant** [edufolly/flutter_bluetooth_serial#52]
Hello!
The `getBondedDevices` call never finishes, it crashes the app.
I'm trying to get now connected device's address. I've gone through the lib code and failed to find this method anywhere so my idea was to get all the paired devices and find the one with BluetoothBondState.bound. IDK if this method gets paired devices or connected devices, this is what I'm testing / trying to figure out.
However... the initial call fails. This is me testing the method:
https://pastebin.com/5cdX052g

Again, I know. Async in build sux. I just wanna see the output.
This is the debug console output doe:
https://pastebin.com/tsvy0nEh

Manifest:
https://pastebin.com/PRG6vcDF

Tried `flutter clean`. Breakpoint just at the call says it has to be that call that breaks the app. Commenting it out works...
2 hours of googlng didn't help.
I'm running linux (obvious from debug message), live device Samsung J7, Android 9.1.
Any ideas?

EDIT: I don't know how Github "code" works but I don't like it. Moved it to mpastebin.

**Comment by PsychoXIVI** [comment]
Hello,

It looks like the main issue is unavailable resolution of AndroidX. 

Which version of the plugin are you using? If still `0.2`, please update to `0.2.1` - there was a some fix related to AndroidX afik.

**Comment by n00ne1mportant** [comment]
Thank you for quick response.
I am using ´0.2.1´. Not using AndroidX. I opened the project with Android Studio to move it to AndroidX via the refactor menu. It gave me "Not using" message and the directory was unchanged.
Is it possible I'm using it the wrong way?
I just don't see it atm might be smtg trivial.
Ideas?
The package file is bellow:
---------
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bluetooth_serial: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by n00ne1mportant** [comment]
Adding 
```
android.useAndroidX=true
android.enableJetifier=true
```
to gradle.properties fixes it :man_facepalming: 

Maybe we could add a note to Readme? It was a solution to similar compile time issue as well. 
Anyways I'll close it now

**Comment by PsychoXIVI** [comment]
I was just about to ask about it :D haha

**Comment by kamilk91** [comment]
@PsychoXIVI the same problem with v0.2.2, and adding 
```
android.useAndroidX=true
android.enableJetifier=true
```
helped.
