### ISSUE TITLE
how to use this plugin (more errors when i use it)

### ISSUE THREAD

**Issue by mouradouddah** [edufolly/flutter_bluetooth_serial#6]

**Comment by edufolly** [comment]
Hi @mouradouddah,
please, provide a new issue with more details about your problems.
You can see the [example](https://github.com/edufolly/flutter_bluetooth_serial/blob/master/example/lib/main.dart) to start to develop your app.

**Comment by mouradouddah** [comment]
hi, I eagerly wait for the new version.

**Comment by edufolly** [comment]
I published a new version of the plugin. Please, make some tests and if you find some problem open a new issue.

**Comment by mouradouddah** [comment]
Yes I tested your new version (**flutter_bluetooth_serial 0.0..4**) and now I communicated **HC05** with my mobile without errors. thank you very much **edufoly** .
                                                      **we are still waiting for you new plugins and updates**
