### ISSUE TITLE
 Method not found: 'BluetoothConnection.toAddress

### ISSUE THREAD

**Issue by gillestasse** [edufolly/flutter_bluetooth_serial#64]
I am using version 0.2.2

```
Compiler message:
file:///Documents/coding/applications/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_bluetooth_serial-0.2.2/lib/FlutterBluetoothSerial.dart:245:52: Error: Method not found: 'BluetoothConnection.toAddress'.
    _defaultConnection = await BluetoothConnection.toAddress(address);
                                                   ^^^^^^^^^
lib/pages/tagReader/devicesList.dart:56:65: Error: Method not found: 'BluetoothConnection.toAddress'.
     BluetoothConnection connection = await BluetoothConnection.toAddress(device.address);
                                                                ^^^^^^^^^
Compiler failed on /Documents/coding/FLUTTER/appf/lib/main.dart
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by gillestasse** [comment]
I created a pull request. Should i close the case ?

**Comment by PsychoXIVI** [comment]
Buddy, you might messed up your repository clone... The function exists all the time - at least for me (checked both my offline copy and remote copy (via GitHub). 

![image](https://user-images.githubusercontent.com/23557839/63356009-5f558a00-c367-11e9-805e-3e2e73a2e5a3.png)

Please double check everything. 🤔

**Comment by gillestasse** [comment]
I installed 0.2.2 by updating dependency to `pubspec.yaml` and check the files locally.

https://drive.google.com/file/d/1ljEzFhOjZnf66_8fufnZ0kt5Uzn_tedh/view?usp=sharing

**Comment by PsychoXIVI** [comment]
And there is it on line no 61, isn't it?

**Comment by gillestasse** [comment]
You are absolutely right. 
I updated from 0.0.5 to 0.2.2
It got me confused I guess...
I did not have it locally, so I got an error.
Well sorry for the inconvenience, I'll delete my pull request.

**Comment by PsychoXIVI** [comment]
I will close related issues too. Please feel free to write if necessary.
