### ISSUE TITLE
There is no method to send data in string format to bluetooth hc-05 like java.io.DataOutputStream.writeBytes(String s)

### ISSUE THREAD

**Issue by SalilLuley** [edufolly/flutter_bluetooth_serial#73]
I want to write data to hc-05 in string format but could not find any method for this in the library. The only method used to write data which I found was output.write method which only accepts Uint8List type of object.

If you can create a method which writes data using string parameter it will be very helpful.
Thanks in advance.

**Comment by PsychoXIVI** [comment]
You just need encode string into format you would like to use (ASCII, UTF-8 and soon).

There is example:
https://github.com/edufolly/flutter_bluetooth_serial/blob/27eb846fead4b44488d2fc9f9f7457e6202ac940/example/lib/BackgroundCollectingTask.dart#L75
Also, you might want to check out full file for whole example.

There is also [API note for `BluetoothConnection` `output`](https://pub.dev/documentation/flutter_bluetooth_serial/latest/flutter_bluetooth_serial/BluetoothConnection/output.html):
> You should use some encoding to send string, for example `.add(ascii.encode('Hello!'))` or `.add(utf8.encode('Cześć!)).`
