### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ert485** [edufolly/flutter_bluetooth_serial#78]
### Problem summary

The LICENSE file is just a todo, and I would like to know how you would like credit attributed and any concerns you have for redistributing/modifying. One similar to [flutter_blue](https://github.com/pauldemarco/flutter_blue/blob/master/LICENSE) would do the trick

**Comment by PsychoXIVI** [comment]
PTAL @edufolly - it was originally your repo, so you should decide. I personally think that MIT would be fine.

PS: It might be useful: https://choosealicense.com/ if you are considering other options.

**Comment by edufolly** [comment]
Sorry about the delay. I added the MIT LICENCE.
Thanks, mates.
