### ISSUE TITLE
How do we print a test with connected printers

### ISSUE THREAD

**Issue by jjoao07** [edufolly/flutter_bluetooth_serial#92]
Hi there,

I have followed the instructions of this plugin, but I can't see a way to print data or send data from the app to the printer.

can you guys please help out how do we print a simple image file or a QR code from the app to a Bluetooth connected printer.

Thanks

**Comment by edufolly** [comment]
Hi João,

you need to use the printer language to communicate. Look at this issue #1 

Best.

**Comment by jjoao07** [comment]
Hi @edufolly thanks for your reply.
My printer is Zebra, Qln320, the function or method I’m looking on is how to call something like `bluethoothPrinter.print()`
Just to send an Hello word to connected printer.

**Comment by edufolly** [comment]
I never integrate this plugin with a BT printer.

I find this interesting information on Zebra's site.
https://www.zebra.com/us/en/support-downloads/printer-software/by-request-software.html

Maybe you need ZPL to print your tag. Hope this helps

**Comment by jjoao07** [comment]
Oi @edufolly muito obrigado ai pela ajuda,
acabei descobrindo que a para fazer a impressao do QR code com essa impressora,
tenho de escrever o ZPL comandos.

so vou tou revisando o manual todo na pagina do Zebra, qualquer coisa dou um sinal.
Bom dia
